default_platform(:android)

platform :android do
  desc 'Run unit & instrumentation tests'
  lane(:test) { test_android }

  desc 'Build & deploy AAB to Google Play (includes metadata)'
  lane(:deploy) { deploy_android }

  desc 'Push Play Store metadata'
  lane(:metadata) { metadata_android }
end
