name: Github Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  call-release-workflow:
    uses: FossifyOrg/.github/.github/workflows/release.yml@main
    with:
      tag: ${{ github.ref_name }}
      flavor: "foss"
      package_name: "org.fossify.gallery"
    secrets: inherit