name: Prepare Release PR

on:
  repository_dispatch:
    types: [prepare-release]
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "CHANGELOG.md"

jobs:
  call-release-pr:
    uses: FossifyOrg/.github/.github/workflows/prepare-release-pr.yml@main
    secrets: inherit
